# Generated by Django 4.0.6 on 2022-08-03 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_groupstudents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupStudents',
            new_name='GroupStudent',
        ),
    ]
