# Generated by Django 4.0.6 on 2022-08-03 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_rename_groupstudents_groupstudent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupStudent',
            new_name='GroupStudents',
        ),
        migrations.AlterModelOptions(
            name='groupstudents',
            options={'verbose_name': 'Group student', 'verbose_name_plural': 'Group students'},
        ),
    ]
